default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: root
  password: root

development:
  <<: *default
  database: proj01_development

test:
  <<: *default
  database: proj01_test

production:
  <<: *default
  database: proj01_production