# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06f0855ba0976c8d9301f07895adfcaf31f7ad0fe9536ce407d376f88eee7c99203a74d8c4e36370fad1d4a12223269a48f433ce3bfe9074ef5b681e9058b8e

test:
  secret_key_base: c58937bb54c7388d03ebb8069d9e428b2f62cd9134b79313860fda6c71eff15a7953181cd32359dcf27ce9eaa9279573c5582316e98a7983439952e50ec7f65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
